---
- name: Patching RHEL
  hosts: all
  become: true

  tasks:
    # Print the message patching RHEL has been starting & Execute subscription-manager identity to check if the system has any active subscriptio & Fail if the previous task did not find any subscription services & Execute yum repolist to check connectivity & Failed if the previous task found a failed in any repository & Update all packages (It takes a while) - (DO NOT CANCEL IT) & Ensure the RPM package [yum-utils] is installed & Execute needs-restarting -r to check if reboot is required & Reboot the system if the previous task failed which means a reboot is required & Print the message patching RHEL has been successfully completed.