---
- name: Perform backup ( Alternate Disk ) for AIX systems
  hosts: all
  gather_facts: false # <--- Disable Gathers facts about remote hosts
  become: true  # <--- Elevated privs

  tasks:

    - name: Perform an alternate disk copy of the rootvg to hdisk1
      # Content suggestion provided by Ansible Lightspeed
      ibm.power_aix.alt_disk:
        action: copy
        targets: hdisk1

    - name: Perform an alternate disk copy of the rootvg to the nearest disk that can be selected
      # Content suggestion provided by Ansible Lightspeed
      ibm.power_aix.alt_disk:
        action: copy
        disk_size_policy: nearest
        allow_old_rootvg: true
        force: true

    - name: Perform an alternate disk copy of the rootvg to the smallest disk that can be selected
      # Content suggestion provided by Ansible Lightspeed
      ibm.power_aix.alt_disk:
        action: copy
        disk_size_policy: minimize

    - name: Perform a cleanup of any existing alternate disk copy
      # Content suggestion provided by Ansible Lightspeed
      ibm.power_aix.alt_disk:
        action: clean

    - name: Perform a cleanup of any existing alternate disk copy and old rootvg
      # Content suggestion provided by Ansible Lightspeed
      ibm.power_aix.alt_disk:
        action: clean
        allow_old_rootvg: true
...
