---
- name: Perform System Image Backup (mksysb) for AIX systems
  hosts: all
  gather_facts: true # <--- Enabled Gathers facts about remote hosts
  become: true  # <--- Elevated privs
  vars:
    start_msg:
      - "************************************************"
      - " Starting create a System Image Backup (mksysb) "
      - "************************************************"
    node_v: nfsserver01.lab.example.com
    mount_dir_value: /mount/nfs
    mount_over_dir_value: /localdir
    location: "{{ mount_over_dir_value }}/{{ inventory_hostname }}-{{ ansible_distribution }}-{{ ansible_distribution_version }}.mksysb"
    dict_assert_backup_msg:
      fail_msg: "FAILED! => mksysb: Backup has failed. Please fix that issue as soon as you get a chance and try again."
      success_msg: "PASSED! => mksysb: Backup Completed Successfully, Proceeding with the next task..."
    final_msg:
      - "*************************************************************************"
      - " SUCCESS! The backup of the system image (mksysb) has been completed !!! "
      - "*************************************************************************"
  tasks:

    # - name: "Print on screen using start_msg var"

    # - name: "Mount NFS share using the ibm.power_aix.mount module with the variables node_v, mount_dir_value and mount_over_dir_value"

    # - name: "Backup the rootvg with ibm.power_aix.backup with action create, type mksysb, location var, exclude_files false and extend_fs"

    # - name: "Assert Backup the rootvg with mksysb with custom message dict_assert_backup_msg var"

    # - name: "Umount NFS share using the ibm.power_aix.mount module with the variable mount_dir_value and force"

    # - name: "Notify | Print on screen using final_msg var"