---
- name: Perform backup ( Alternate Disk ) for AIX systems
  hosts: all
  gather_facts: false # <--- Disable Gathers facts about remote hosts
  become: true  # <--- Elevated privs
  vars:
    dict_assert_msg:
      fail_msg: "FAILED! => No evidence found in logs that Alternate Disk finished successfully. Fix that issue as soon as you get a chance and try again."
      success_msg: "PASSED! => Cloning a rootvg using an (Alternate Disk) copy was successful. Proceeding to the next task..."
  tasks:

    # - name: "Perform a cleanup of any existing alternate disk copies using alt_disk with the clean action"
    
    # - name: "Run an alternate disk copy from rootvg using alt_disk module with the copy action and the targets hdisk1"

    # - name: "Assert 'Fixing file system superblocks...' in stdout output at previous task and using {{ dict_disk_assert }}"